In [ ]:
import pandas as pd
import numpy as np
df = pd.read_csv("/content/drive/MyDrive/IBM/CSV/Products.csv")
df

      Product  Price
0      Laptop  50000
1      Mobile  20000
2   Headphone   3000
3      Tablet  25000
4  Smartwatch   8000
5     Charger    250
6   USB cable     50
7   PowerBank    800

In [ ]:
products = {
    "Products":["Laptop","Mobile","Headphones","Tablet","Smartwatch","Charger","USB cable","PowerBank","Guard","Earpods","Speaker"],
    "Price":[50000,20000,3000,25000,5000,1000,50,1000,50,1200,4000]
}
df1 = pd.DataFrame(products)
df1

      Products  Price
0       Laptop  50000
1       Mobile  20000
2   Headphones   3000
3       Tablet  25000
4   Smartwatch   5000
5      Charger   1000
6    USB cable     50
7    PowerBank   1000
8        Guard     50
9      Earpods   1200
10     Speaker   4000

In [ ]:
avg_price = np.mean(df["Price"])
print ("Average Price : ",avg_price)

Average Price :  13387.5

In [ ]:
def above_avg_price(data, avg):
  print("Product above average: ")
  for i in range(len(data)):
    if data["Price"][i]> avg:
            print(data["Product"][i], "-", data["Price"][i])
above_avg_price(df, avg_price)

Product above average:
Laptop - 50000
Mobile - 20000
Tablet - 25000

Ques 2

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/IBM/CSV/Day,Temperature.csv")
df

         Day  Temperature
0     Monday           18
1    Tuesday           25
2  Wednesday           32
3   Thursday           28
4     Friday           15
5   Saturday           35
6     Sunday           22

In [ ]:
highest_temp = np.max(df["Temperature"])
print("Highest Temp :", highest_temp)
lowest_temp = np.min(df["Temperature"])
print("lowest Temp :", lowest_temp)
Average_Temp = np.mean(df["Temperature"])
print ("Average Temp :", Average_Temp)

Highest Temp : 35
lowest Temp : 15
Average Temp : 25.0

In [ ]:
def classify(temp):
  if temp < 20:
    print ("cold")
  elif temp > 30:
    print("hot")
  else:
    print ("moderate")
print("\nTemperature Categories:")
for i in range(len(df)):
    day = df["Day"][i]
    temp = df["Temperature"][i]
    category = classify(temp)
    print(day, "-", temp, "°C :", category)

Temperature Categories:
cold
Monday - 18 °C : None
moderate
Tuesday - 25 °C : None
hot
Wednesday - 32 °C : None
moderate
Thursday - 28 °C : None
cold
Friday - 15 °C : None
hot
Saturday - 35 °C : None
moderate
Sunday - 22 °C : None